#!/bin/sh

[ "$ACTION" = ifup ] || exit 0

# Is adhoc interface?
MODE=$(uci get wireless.$INTERFACE.mode)
[ "$MODE" = adhoc ] || exit 0

# ddmesh bootstrapped?
MIDDLE=$(uci get ddmesh.system.node_middle)
MINOR=$(uci get ddmesh.system.node_minor)
[ -n "$MIDDLE" ] || [ -n "$MAJOR" ] || exit 0

# Add ddmesh address:
ip addr add 10.200.$MIDDLE.$MINOR/16 dev $DEVICE brd 10.255.255.255
